version: "3.8"
services:
  frontend:
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3412:3412"
    environment:
      - EXPO_WEB_PORT=3412
    depends_on:
      - backend
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8194 --reload
    env_file:
      - .env
    ports:
      - "8194:8194"
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
volumes:
  db-data:
