name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint backend
        run: |
          cd backend
          flake8 . --max-line-length 200 --extend-ignore=E302,E402,E305,W291,W293,W391,E128,E122

      - name: Run backend tests
        run: |
          cd backend
          pytest

      - name: Build backend Docker image
        run: docker build -t kinlia-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t kinlia-frontend ./frontend
